 POST http://localhost:8000/api/users/signin/

 Content-Type: "application/json"

 {
  "email": "test",
  "password": "test" ,
   }

###

GET http://localhost:8000/api/newly-added-products

 Content-Type: "application/json"
